### ISSUE TITLE
customization "dev" fails

### ISSUE THREAD

**Issue by onceatime** [hashicorp/otto#106]
also if specified
````
customization "dev" {
    vagrantfile = "./Vagrantfile"
}
````
it fails with
````
Error building dev environment: Otto can't build a development environment for this because the
"vagrant" setting hasn't been set in the "dev" or "dev-dep" customization.

For the "custom" application type, customizations must be used to
tell Otto what to do. For the dev command, Otto requires either
the "dev" or "dev-dep" customization to be set with the "vagrant" setting.
The "vagrant" setting depends on which customization is being set. Please
refer to the documentation for more details.

Example:

    customization "dev" {
        vagrant = "path/to/Vagrantfile"
    }
````

**Comment by girishpandit88** [comment]
Have exact issue. Also the Error message wrongly says vagrant, whereas documentation says vagrantfile https://github.com/hashicorp/otto/blob/master/builtin/app/custom/app.go#L273

**Comment by noisebleed** [comment]
+1 in OS X Yosemite.

**Comment by sporto** [comment]
Same issue (otto 0.1.1) MacOS 10.11

**Comment by mitchellh** [comment]
This is fixed in master!

**Comment by noisebleed** [comment]
Thanks @mitchellh. Was this included in 0.1.2?

**Comment by stavro** [comment]
I still get this error with v0.2.0.

```

$ otto -v
Otto v0.2.0

$ otto dev
Error building dev environment: Otto can't build a development environment for this because the
"vagrant" setting hasn't been set in the "dev" or "dev-dep" customization.

For the "custom" application type, customizations must be used to
tell Otto what to do. For the dev command, Otto requires either
the "dev" or "dev-dep" customization to be set with the "vagrant" setting.
The "vagrant" setting depends on which customization is being set. Please
refer to the documentation for more details.

Example:

    customization "dev" {
        vagrantfile = "path/to/Vagrantfile"
    }


$ cat Appfile 
application {
    name = "my-app"
    type = "custom"
}

customization "dev" {
    vagrantfile = "./Vagrantfile"
}

customization "deploy" {
    terraform = "./terraform-module"
}


$ ls Vagrantfile 
Vagrantfile

```

**Comment by stavro** [comment]
Update:  Looks like the syntax has changed to:

```
customization {
  dev_vagrantfile = "./Vagrantfile"
  terraform = "./terraform-module"
}
```

This appears to let me get to the next step

**Comment by vansickle** [comment]
Still the same bug with otto 0.2.0 on OS X. Thanks to @stavro - it works. You should update docs or otto.
